init:
  plugins:
    - clean
    - packagejson
settings:
  coffee: './node_modules/.bin/coffee'
  clean:
    path: ['lib', 'build']
  srcPath: 'src'
  libPath: 'lib'
  mocha:
    useCoffee: true
build:
  - '%coffee% -b -o %libPath% -c %srcPath%'
  - echo Build done.
install:
  - task: build
  - echo Install done.
